# fly.toml app configuration file generated for alpaca-processor-v1 on 2025-04-07T22:13:30-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'alpaca-processor-v1'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
